version: '3.7'

services:

    php:
        build: php
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}

    server:
        build: ./server
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}
        # restart: always
        environment:
            - NGINX_HOST=localhost
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}